### ISSUE TITLE
MimeType getting null for audio files

### ISSUE THREAD

**Issue by Softkeydel** [mitsuoka/mime_type#17]
mime() function returning null for various audio files like .m4a, .mp3, .acc, .amr

Please help

**Comment by Molkars** [comment]
The lookupMimeType function is part of the mime library found here [Dart-Lang Mime](https://github.com/dart-lang/mime), not a part of this library.

**Comment by Softkeydel** [comment]
sorry for the previous wrong information
mime() function returning null sometimes for various audio files like .m4a, .mp3, .acc, .amr

Please help

**Comment by Molkars** [comment]
It's to determine your issue without being able to see your code. I'd suggest checking that your input string isn't null or empty and that the file doesn't have some sub-extension (`.mp4.tsv` for instance).

**Comment by Molkars** [comment]
Issue is stale, will re-open if further assistance is required
