### ISSUE TITLE
File type "image/bmp" is not supported propertly.

### ISSUE THREAD

**Issue by ollydixon** [mitsuoka/mime_type#19]
```file --mime-type -b /Users/me/Downloads/74ab8f4f5e2e74805eb3fe1eb717dfe2 ```

On Mac shows "image/bmp"

On  Flutter it returns "image/jpg"

We need to know if it's "image/bmp" for server-side processing reasons.

User generated file below (very old test photo of me)

![74ab8f4f5e2e74805eb3fe1eb717dfe2](https://user-images.githubusercontent.com/6940726/159559706-7be72da5-c51e-4e2e-9006-99aba0a37dc9.jpg)

**Comment by Molkars** [comment]
It's a bitmap image mislabeled as a jpg.

**Comment by ollydixon** [comment]
@Molkars might be some Github thing that's compressed and converted it. Here is a direct link https://www.dropbox.com/t/o3QdorvooW4kcSzj

I even looked at the first 2 bits locally and it says it's BMP.

**Comment by Molkars** [comment]
It's weird that it is uploaded on dropbox as a .jpg as well.

**Comment by Molkars** [comment]
I think the file command probably checks the first few bytes of the file and gets the type based on that whereas this package just uses the extension. If you want it to check the header bytes, try the dart team's mime package.

**Comment by ollydixon** [comment]
@Molkars thanks for the support. There's a native one or I have to download it? Can't seem to find it :-D

**Comment by Molkars** [comment]
@ollydixon
https://pub.dev/packages/mime. You do have to do a little bit of work to read the first few header bytes but it will give you the correct file type nearly everytime.

**Comment by ollydixon** [comment]
@Molkars yeah I just did it manually, then convert it via app.

```
  // Is BMP, convert.
        if (listEquals([0x42, 0x4d], [newBytes[0], newBytes[1]])) {
          mime = "image/bmp";
          // Get bytes for this. Convert to jpeg.
          final image = image_lib.decodeImage(newBytes)!;
          bytes = Uint8List.fromList(image_lib.encodePng(image));
          path = null;
        }
      }
```
