### ISSUE TITLE
There should be a method to match the type

### ISSUE THREAD

**Issue by d-silveira** [mitsuoka/mime_type#3]
Once we get the mimeType, in uses other than web requests, it would be useful to have a method to which we can match the type to a group, for instance: ` isType(VIDEO, mime(filePath)) `

**Comment by mitsuoka** [comment]
The mime_type Pub package is very simple library for HTTP server applications that was developed in the early stages of Dart language development.
After that, Dart team developed [mime package](https://pub.dartlang.org/documentation/mime/latest/mime/mime-library.html) that was expanded to cope with MIME multipart requests.
My suggestion is to ask dart team to add such additions to the mime package that is well maintained by the team. I am a retired old engineer and accepting only new MIME type additions now.

Is “group” in your comment equivalent to the top level “type” of IETF media type format?
`  type "/" [tree "."] subtype ["+" suffix] *[";" parameter]`
If so, such method is very simple such as:
```dart
// new method proposed by d-silveira
bool isType(String group, String filePath) {
  String mimeType = mime(filePath);  // get MIME type of the file
  if (mimeType == null) return null;
  RegExp exp = new RegExp(r"(\w+)"); // get top level "type" portion
  String type = exp.stringMatch(mimeType);
  return group.toLowerCase() == type;
}
// test code
main() {
  String filePath = 'C:\dart_codes\mime_type\lib\mime_type.dart';
  print(isType('APPLICATION', filePath));
}
```

**Comment by d-silveira** [comment]
thanks @mitsuoka I'll bug them instead

**Comment by mitsuoka** [comment]
Good luck.
