### ISSUE TITLE
Cannot import library

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [mitsuoka/mime_type#5]
I get this error on the following import

```
import 'package:mime_type/mime_type.dart';
>Error: Could not resolve the package 'mime_type' in 'package:mime_type/mime_type.dart'.
```

I added the package to my dependencies as follows

pubspec.yaml:
```
dependencies:
  mime: ^0.9.1
```

I did run flutter pub get before running my app

**Comment by mitsuoka** [comment]
There is no version 0.9.1 in Pub package ["mime_type"](https://pub.dev/packages/mime_type/versions).
My suggestion is to use "any" instead.
See my [code sample](https://github.com/mitsuoka/file_server/blob/master/pubspec.yaml).

**Comment by mitsuoka** [comment]
If you are using both "mime" and "mime_type" in your application, use "mime" only.
The "mime_type" Pub package is very simple library for HTTP server applications that was developed in the early stages of Dart language development.
After that, Dart team developed "mime" package that was expanded to cope with MIME multipart requests.
